Repository pungdong/PungDong, pull requests merged in 2021-06, with the labels that each got.

#91 community stack 추가
  ios/Podfile.lock
  package.json
  src/components/CommunityDetail/CommunityDetailMain.tsx
  src/components/CommunityDetail/DetailComments.tsx
  src/components/CommunityDetail/DetailContents.tsx
  src/components/CommunityDetail/DetailInfo.tsx
  src/components/CommunityDetail/index.tsx
  src/components/CommunityDetail/styles.ts
  src/components/CommunityMain/AddContentButton.tsx
  src/components/CommunityMain/CommunityItem.tsx
  src/components/CommunityMain/CommunityList.tsx
  src/components/CommunityMain/CommunityMain.tsx
  src/components/CommunityMain/index.tsx
  src/components/CommunityMain/styles.ts
  src/components/CommunityMain/types.ts
  src/components/CommunityPosting/AddImage.tsx
  src/components/CommunityPosting/CommunityPostingMain.tsx
  src/components/CommunityPosting/EditCompleteButton.tsx
  src/components/CommunityPosting/SelectCategory.tsx
  src/components/CommunityPosting/SelectTag.tsx
  src/components/CommunityPosting/TitleAndContents.tsx
  src/components/CommunityPosting/index.tsx
  src/components/CommunityPosting/styles.ts
  src/components/SetPassword/SetPassword.tsx
  src/navigators/CommunityStack/index.tsx
  src/navigators/CommunityStack/types.ts
  src/navigators/LoginStack/index.tsx
  src/screens/CommunityDetail/index.tsx
  src/screens/CommunityDetail/styles.ts
  src/screens/CommunityMain/index.tsx
  src/screens/CommunityMain/styles.ts
  src/screens/CommunityPosting/index.tsx
  src/screens/CommunityPosting/styles.ts
  src/screens/SetPassword/index.tsx
Labels: enhancement

#132 feat: LetureDetail screen UI 완성
  App.tsx
  ios/DiveInto.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/LectureDetail/AdditionalService/index.tsx
  src/components/LectureDetail/AdditionalService/styles.ts
  src/components/LectureDetail/InstructorProfile/index.tsx
  src/components/LectureDetail/InstructorProfile/styles.tsx
  src/components/LectureDetail/LectureInfo/index.tsx
  src/components/LectureDetail/LectureInfo/styles.ts
  src/components/LectureDetail/LecturePicsCarousel/index.tsx
  src/components/LectureDetail/LecturePicsCarousel/styles.ts
  src/components/LectureDetail/LectureReview/PersonalReview.tsx
  src/components/LectureDetail/LectureReview/Pics.tsx
  src/components/LectureDetail/LectureReview/ReserveBtn.tsx
  src/components/LectureDetail/LectureReview/index.tsx
  src/components/LectureDetail/LectureReview/styles.ts
  src/components/LectureDetail/LectureReview/types.ts
  src/components/LectureDetail/LocationInfo/index.tsx
  src/components/LectureDetail/LocationInfo/styles.tsx
  src/lib/utils/addCashComma.ts
  src/navigators/LectureStack/index.tsx
  src/navigators/LectureStack/types.ts
  src/navigators/LoginStack/index.tsx
  src/recoil/LectureStack.ts
  src/screens/LectureDetail/index.tsx
  src/screens/LectureDetail/styles.ts
  src/screens/UploadTest.tsx
Labels: enhancement

#126 [Community main] issue resolves
  ios/Podfile.lock
  src/components/CommunityDetail/CommunityDetailMain.tsx
  src/components/CommunityDetail/DetailComments.tsx
  src/components/CommunityDetail/DetailContents.tsx
  src/components/CommunityDetail/DetailInfo.tsx
  src/components/CommunityDetail/EditButton.tsx
  src/components/CommunityDetail/index.tsx
  src/components/CommunityDetail/styles.ts
  src/components/CommunityMain/AddContentButton.tsx
  src/components/CommunityMain/CommunityItem.tsx
  src/components/CommunityMain/CommunityList.tsx
  src/components/CommunityMain/CommunityMain.tsx
  src/components/CommunityMain/index.tsx
  src/components/CommunityMain/styles.ts
  src/components/CommunityMain/types.ts
  src/components/CommunityPosting/AddImage.tsx
  src/components/CommunityPosting/AddImages.tsx
  src/components/CommunityPosting/CommunityPostingMain.tsx
  src/components/CommunityPosting/EditCompleteButton.tsx
  src/components/CommunityPosting/SelectBox.tsx
  src/components/CommunityPosting/SelectCategory.tsx
  src/components/CommunityPosting/SelectTag.tsx
  src/components/CommunityPosting/TitleAndContents.tsx
  src/components/CommunityPosting/index.tsx
  src/components/CommunityPosting/styles.ts
  src/components/CommunityPosting/types.ts
  src/lib/file/filePicker.ts
  src/navigators/CommunityStack/index.tsx
  src/navigators/CommunityStack/types.ts
  src/navigators/MainTab/index.tsx
  src/screens/CommunityDetail/index.tsx
  src/screens/CommunityMain/index.tsx
  src/screens/CommunityPosting/index.tsx
  src/screens/CommunityPosting/styles.ts
  testData.json
Labels: UI/UX, refactoring, 스프린트

#136 [Community Stack] 기능 추가 및 보완
  ios/DiveInto.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  src/components/CommunityMain/CommunityItem.tsx
  src/components/CommunityMain/CommunityList.tsx
  src/components/CommunityMain/CommunityMain.tsx
  src/components/CommunityMain/index.tsx
  src/components/CommunityMain/styles.ts
  src/components/CommunityMain/types.ts
  src/components/CommunityPosting/AddImages.tsx
  src/navigators/CommunityStack/types.ts
  src/navigators/LoginStack/index.tsx
  src/screens/CommunityMain/index.tsx
  testData.json
Labels: UI/UX, refactoring
